#!/bin/bash
### BEGIN INIT INFO
# Provides:          ec2-get-credentials
# Required-Start:    $remote_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Retrieve the ssh credentials and add to authorized_keys
# Description:
#
### END INIT INFO

prog=$(basename $0)
logger="logger -t $prog"

public_key_url=http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key
public_key_file=/tmp/openssh_id.pub
public_key_ephemeral=/mnt/openssh_id.pub
authorized_keys=/root/.ssh/authorized_keys

while true; do
    curl --connect-timeout 1 --max-time 2 169.254.169.254:80 > /dev/null 2>&1 && break
    sleep 1;
done

# Try to get the ssh public key from instance data.
curl --silent --fail -o $public_key_file $public_key_url
test -d /root/.ssh || mkdir -p -m 700 /root/.ssh
if [ $? -eq 0 -a -e $public_key_file ] ; then
  if ! grep -s -q -f $public_key_file $authorized_keys
  then
    cat $public_key_file >> $authorized_keys
    $logger "New ssh key added to $authorized_keys from $public_key_url"
  fi
  chmod 600 $authorized_keys
  rm -f $public_key_file
fi
